### ISSUE TITLE
Getting service unavailable

### ISSUE THREAD

**Issue by ccokee** [EnterpriseDB/cloud-native-postgresql-helm#40]
Good morning!
I'm deploying this chart in a baremetal k8s cluster created with kubeadm. After installing the repo and issuing the helm install as:

```
helm upgrade --install cnp --namespace psotgresql-operator-system --create-namespace --set service.type=N
odePort,service.port=30443 cnp/cloud-native-postgresql
```
All seems fine (Deployment shows ready status). But when I try to create a new cluster I get this error:
```
Error from server (InternalError): error when creating "cluster.yaml": Internal error occurred: failed calling webhook "mcluster.kb.io": failed to call webhook: Post "https://postgresql-operator-webhook-service.postgresql-operator-system.svc:443/mutate-postgresql-k8s-enterprisedb-io-v1-cluster?timeout=10s": Service Unavailable
```

My operator is using 30443 as service port so I don't know:
Why is asking in port 443?
Why kubernetes cluster name is not appended after .svc in the url?

Please note: This happens even when I try with ClusterIP and standar port, but just triend 30443 instead and didn't work either.

Have a nice day and thank you so much.

**Comment by phisco** [comment]
You are right, we are not setting the port parameter in the mutating and validating webhooks: e.g. https://github.com/EnterpriseDB/cloud-native-postgresql-helm/blob/main/charts/cloud-native-postgresql/templates/mutatingwebhookconfiguration.yaml#L31

**Comment by ccokee** [comment]
Sorry, the kube-apiserver was using wrong PROXY settings. But still cant set a different port for the service :/
